### ISSUE TITLE
Calibration procedure

### ISSUE THREAD

**Issue by wxmerkt** [hans-robot/elfin_robot#10]
Hi, our arm is out of calibration, i.e., it is not straight anymore in the home position despite the correct count_zeros value. We assume this to be due to pulse mismatch. Do you have a procedure for recalibrating the count_zeros?

**Comment by onionsflying** [comment]
Hi, you can move the arm to the straight position and then use the service `elfin_ros_control/elfin/get_current_position` to get the current encoder value i.e. the current count_zeros.

**Comment by wxmerkt** [comment]
Awesome, thank you. We did not notice any alignment marks on the robot - should there be any markings (as on other manufacturers’ robots)?

**Comment by onionsflying** [comment]
Unfortunately, Elfin doesn't have alignment marks. We are planning to add alignment marks in the future.

**Comment by wxmerkt** [comment]
Thank you, I have visually aligned and look very much forward to alignment marks in future versions.

**Comment by nisrinelr** [comment]
> Hi, you can move the arm to the straight position and then use the service `elfin_ros_control/elfin/get_current_position` to get the current encoder value i.e. the current count_zeros.

Hi, the service you gave was for ros1 right ? can you please give me the one for ros2 ? cuz also my elfin3 robot is out of calibration that it shows weird pose on rviz ... and we didn't get the drivers.yaml file from the vendor with the robot ... thanks for the support
