### ISSUE TITLE
请问在机器人端如何配置？

### ISSUE THREAD

**Issue by spy14414** [hans-robot/elfin_robot#11]
您好，ROS这一端的介绍很详细，也看了你们的Elfin5说明，但是关于机器人端ROS编程这一块并未涉及，不需要在机器人端接受ROS传过来的信息吗？

**Comment by onionsflying** [comment]
您好，ROS使用EtherCAT总线直接控制机器人本体，不通过控制箱，也不需要在机器人端进行编程。

**Comment by spy14414** [comment]
谢谢你。EtherCAT总线，是你们提供的硬件吗。它是类似PLC的东西吗？QAQ

**Comment by onionsflying** [comment]
EtherCAT是总线协议，使用网线作为线缆即可。我们会提供一个转接器，用来把机器人的插头转换成网口。
