### ISSUE TITLE
Safety under ROS control

### ISSUE THREAD

**Issue by rokusottervanger** [hans-robot/elfin_robot#12]
Hello, and thank you for the great ROS support. We got our robot working in just a few hours. 

We noticed that using the ROS controller, the torque threshold safety is disabled, meaning that it's not safe to operate the robot close to humans. Is there any way to enable this? Or is it something that should be implemented in the ROS-driver?

**Comment by onionsflying** [comment]
Hi, thanks for purchasing the robot. Unfortunately, there is no torque threshold safety when you use this ros package. So please be careful while operating the robot.

**Comment by crNewton** [comment]
> Unfortunately, there is no torque threshold safety when you use this ros package. So please be careful while operating the robot.

We noticed that a fault gets raised when we obstruct the robot.
So it looks like there is some form of torque treshold. (following the effort limitations in the urdf).
The fault gets raised by 'ElfinEtherCATDriver::getFaultState()' and is published on 'elfin_ros_control/elfin/fault_state' 

Is there more information available about this torque treshold & the cause of failure/warning?

**Comment by nicola-sysdesign** [comment]
We would like to use your robots controlled by ROS to build some industrial solutions for our customers. Unfortunately it's a 'NO GO' if we can't have safety features.
Ideally I think it should be solved adding your Safety Controller to the EtherCAT chain so it can check that joint torques, speeds, accelerations, etc., don't exceed safety ranges and take action in case they do.
Are there any plans to implement it or thoughts about it? Thanks
