### ISSUE TITLE
ABORTED: No motion plan found. No execution attempted.

### ISSUE THREAD

**Issue by trgyada** [hans-robot/elfin_robot#13]
hi  i'm trying to image processing with elfin3. Now i'm just write a basically node but this is not running. I get this error. 

[ INFO] [1548061701.023107198, 16.268000000]: ABORTED: No motion plan found. No execution attempted.

this is my python code;

moveit_commander.roscpp_initialize(sys.argv)
roscpp_initialize(sys.argv)

rospy.init_node("move", anonymous=True)

display_trajectory_publisher = rospy.Publisher('/move_group/display_planned_path', moveit_msgs.msg.DisplayTrajectory, queue_size=20)

    
robot = moveit_commander.RobotCommander()
scene = moveit_commander.PlanningSceneInterface()
group = moveit_commander.MoveGroupCommander("elfin3_arm")

elfin3_arm = MoveGroupCommander("elfin3_arm")
elfin3_arm.set_goal_orientation_tolerance(0.005)
elfin3_arm.set_planning_time(5)
elfin3_arm.set_num_planning_attempts(5) 
rospy.sleep(2)
elfin3_arm.allow_replanning(True)
      
rospy.sleep(1)

p = PoseStamped()
p.header.frame_id = robot.get_planning_frame()

p.pose.position.x = 1
p.pose.position.y = 1
p.pose.position.z = 1

p.pose.orientation.w = 1.0

elfin3_arm.set_pose_target(p)
elfin3_arm.go(wait=True)

rospy.spin()
roscpp_shutdown()

**Comment by onionsflying** [comment]
This answer might be helpful: https://answers.ros.org/question/240723/fail-aborted-no-motion-plan-found-no-execution-attempted/
