### ISSUE TITLE
wsl2 EtherCat issues when connecting to a real robot.

### ISSUE THREAD

**Issue by jin-technoaccord** [hans-robot/elfin_robot#29]
Hi community, I am facing issues with etherCat when I try to run following:
$ sudo chrt 10 bash
$ roslaunch elfin_robot_bringup elfin_ros_control.launch

Error message is saying that 
"No slaves are found on eth0
terminate called after throwing an instance of 'elfin_ethercat_driver::EtherCatError'
  what():  Could not initialize SOEM"

hardware connection is made properly. I am running ubuntu 18.04 for WSL2. Any help will be appreciate it.

**Comment by awupereda** [comment]
Hi, did you manage to solve your problem? I've been facing the same issue and haven't been able to connect to the real robot
