### ISSUE TITLE
Adapter to connect Elfin to Computer still necessary?

### ISSUE THREAD

**Issue by endu-code** [hans-robot/elfin_robot#31]
Hi
As I have seen in the issue from 2018 (referenced below) the elfin Robot should/can not be connected to ROS over the control Unit. Is this a must, or just a recommendation? Are there ways to use ROS over the control unit?

I also tried to contact the maintainer of the repo over the contact statet on http://wiki.ros.org/Robots/Elfin for other questions I think are not worthy to open an Issue. Is this the current contact for this or should I contact Shenzhen Han's Robot Co. for ROS related questions?

_Originally posted by @onionsflying in https://github.com/hans->robot/elfin_robot/issues/7#issuecomment-402581071_

>Hi, the Elfin should be connected directly to a computer, without the control box. In this >case, you need such an adapter: [Elfin cable adapter.pdf](https://github.com/hans->robot/elfin_robot/files/2164590/Elfin.cable.adapter.pdf)

>By the way, there is no need to set IP address for EtherCAT connection.

**Comment by awupereda** [comment]
Hi, I was checking this [manual](https://www.elfinrobot.nl/download/documents/HR-Elfin-User_Manual.pdf) for the Elfin robot, and on pages 124 through 128 they mention that you can connect to Elfin robot with two methods: 1) Power the robot with an electric cabinet, and 2) Use external power to power the robot using the LAN-to-LAN adapter.

> right now the only way to connect to the robot via ROS is to connect the LAN cable from the robot directly to your computer

My question is if I should dismiss the first method mentioned in the manual and buy the LAN adapter. At the moment I'm using  the first method and I'm getting the same error as #7.
