### ISSUE TITLE
MoveIt Setup Assistant cannot edit config pack

### ISSUE THREAD

**Issue by Qf001** [hans-robot/elfin_robot#32]
Hi I tried to open the elfin3_moveit_config package to edit it and was bugged by this error.

![Screenshot from 2021-10-17 12-06-00](https://user-images.githubusercontent.com/90997219/137610913-ee5cf3b9-aac2-4eae-aae1-5efa64f78b22.png)

Also, i alternatively tried creating a new config package with elfin3.urdf.xacro and faced more errors.

![Screenshot from 2021-10-17 12-05-20](https://user-images.githubusercontent.com/90997219/137610941-fe7feffa-bf83-4d6f-aa9e-f3784655858b.png)
![Screenshot from 2021-10-17 12-05-41](https://user-images.githubusercontent.com/90997219/137610991-18ed6e4b-6953-4357-af4e-869645d3f3d7.png)

My intended purpose here was to add my own end effectors to the existing elfin3 using my stl files.
Please advise if my methods are correct thanks!

**Comment by crNewton** [comment]
looks like you forgot to source your workspace, this needs to be done so the setup_assistent can find the packages.
