### ISSUE TITLE
RS485 api setup

### ISSUE THREAD

**Issue by jwwood3** [hans-robot/elfin_robot#36]
I have an Elfin5 arm and I'm trying to use the RS 485 communication ports on the end of arm connector, but I can't figure out how to program it to send and receive data in ros. The api documentation doesn't seem to have anything for this, though the readme mentions a separate v3 launch file that doesn't seem to exist anymore. I've been using the ros python libraries with ros noetic on an Ubuntu 20.04 virtual machine.

**Comment by Neverforgetlove** [comment]
If you use RS485, then use the standard branch noetic.
You can control terminal IO through this service: elfin_ros_control/elfin/io_port1/write_do (elfin_robot_msgs/ElfinIODWrite)
and you can find it in docs/API_description.md
You can refer the img to control the DO output, it only have three DO
![ec5b9ecc460b186f78ac616b6781900](https://github.com/hans-robot/elfin_robot/assets/39668522/3d5fa9d0-682f-494f-aca4-d265810e5deb)

**Comment by jwwood3** [comment]
Thank you for the quick response. This is the pinout I have for the end of arm connector. 
![Screenshot_20230619_183255](https://github.com/hans-robot/elfin_robot/assets/60763121/e631939c-58f0-4ee6-80fc-0d85a3732c24)

It shows the three DO ports as pins 4,5, and 6. Then pins 7 and 8 are the RS 485 connections. Can I access those ports?

**Comment by Neverforgetlove** [comment]
You can only control the DO ports as pins 4,5, and 6, and do not support to control rs485
