### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by Soil-L** [hans-robot/elfin_robot#44]
in elfin_basic_api/CMakeLists.txt

```
catkin_package(
  INCLUDE_DIRS include
  LIBRARIES elfin_basic_api
  CATKIN_DEPENDS moveit_core moveit_ros_planning moveit_ros_planning_interface roscpp rospy tf tf_conversions
  DEPENDS system_lib
)
```

may cause building error like [link](https://answers.ros.org/question/288967/build-package-with-system_lib-not-found/)

**Comment by Neverforgetlove** [comment]
Which branch are you using?

**Comment by Soil-L** [comment]
> Which branch are you using?

Sorry.  i mistook warning for error. In fact, the project compiles fine.

i am using 
* ubuntu 18.04 + melodic
* brunch: melodic
